version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/wp-content/themes

permissions:
  owner: ec2-user
  group: apache

hooks:
  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 15
      runas: root
